package com.digitalwallet.model;

import java.io.Serializable;
import java.time.LocalDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.digitalwallet.converter.LocalDateTimeToStringTypeConverter;

@DynamoDBTable(tableName = "Fileinfo")
public final class Fileinfo implements Serializable{

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
    private String tuid;
    private String fileName;
    private String pnr;
    private String tripId;
    @DynamoDBTypeConverted(converter = LocalDateTimeToStringTypeConverter.class)
    @DynamoDBTyped(DynamoDBAttributeType.S)
    private LocalDateTime uploadedTime;
    
    
    
    
    
    
    
    public Fileinfo() {
		super();
	}
	public Fileinfo( String tuid, String fileName, String pnr, String tripId, LocalDateTime uploadedTime) {
		super();
		this.tuid = tuid;
		this.fileName=fileName;
		this.pnr = pnr;
		this.tripId = tripId;
		this.uploadedTime = uploadedTime;
	}
   
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute(attributeName = "tuid")
	public String getTuid() {
		return tuid;
	}
	public void setTuid(String tuid) {
		this.tuid = tuid;
	}
	@DynamoDBAttribute(attributeName = "pnr")
	public String getPnr() {
		return pnr;
	}
	public void setPnr(String pnr) {
		this.pnr = pnr;
	}
	@DynamoDBAttribute(attributeName = "tripId")
	public String getTripId() {
		return tripId;
	}
	public void setTripId(String tripId) {
		this.tripId = tripId;
	}
	@DynamoDBAttribute(attributeName = "uploadedTime")
	public LocalDateTime getUploadedTime() {
		return uploadedTime;
	}
	public void setUploadedTime(LocalDateTime uploadedTime) {
		this.uploadedTime = uploadedTime;
	}
	@DynamoDBAttribute(attributeName = "fileName")
	public String getFileName() {
		return fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
    
    
    
    
}
