package com.digitalwallet.model;

import java.io.Serializable;
import java.time.LocalDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.digitalwallet.converter.LocalDateTimeToStringTypeConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;

@DynamoDBTable(tableName = "Fileinfo")
public final class Fileinfo implements Serializable{

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
    private String tuid;
    private String fileName;
    private String pnr;
    private String tripitem;
    @DynamoDBTypeConverted(converter = LocalDateTimeToStringTypeConverter.class)
    @DynamoDBTyped(DynamoDBAttributeType.S)
    private LocalDateTime startDate;
    
    
    
    
    
    
    
    public Fileinfo() {
		super();
	}
	public Fileinfo( String tuid, String fileName, String pnr, String tripitem, LocalDateTime startDate) {
		super();
		this.tuid = tuid;
		this.fileName=fileName;
		this.pnr = pnr;
		this.tripitem = tripitem;
		this.startDate = startDate;
	}
   
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getTuid() {
		return tuid;
	}
	public void setTuid(String tuid) {
		this.tuid = tuid;
	}
	
	public String getPnr() {
		return pnr;
	}
	public void setPnr(String pnr) {
		this.pnr = pnr;
	}
	public String getTripitem() {
		return tripitem;
	}
	public void setTripitem(String tripitem) {
		this.tripitem = tripitem;
	}
	public LocalDateTime getStartDate() {
		return startDate;
	}
	public void setStartDate(LocalDateTime startDate) {
		this.startDate = startDate;
	}
	public String getFileName() {
		return fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
    
    
    
    
}
